CREATE TABLE fazenda (
id_fazenda      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome_fazenda    VARCHAR2(100)   NOT NULL,
area_hectares   NUMBER(10,2),
regiao_fazenda  VARCHAR2(50)
);

CREATE TABLE cultura (
id_cultura      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome_cultura    VARCHAR2(80) NOT NULL,
ciclo_meses     NUMBER(3)
);

CREATE TABLE producao (
id_producao     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
id_fazenda      NUMBER  NOT NULL,
id_cultura      NUMBER NOT NULL,
ano_safra       NUMBER(4) NOT NULL,
quant_tonelada  NUMBER(12,2),
custo_total     NUMBER(14,2),
receita_total   NUMBER(14,2),
CONSTRAINT fk_producao_fazenda FOREIGN KEY (id_fazenda) REFERENCES fazenda(id_fazenda),
CONSTRAINT fk_producao_cultura FOREIGN KEY (id_cultura) REFERENCES cultura(id_cultura)
);

CREATE TABLE maquinarios (
id_maquinario       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
id_fazenda          NUMBER NOT NULL,
nome_maquinario     VARCHAR2(80) NOT NULL,
tipo_maquinario     VARCHAR2(50) NOT NULL,
custo_hora          NUMBER(10,2)  NOT NULL,
horas_trabalhadas   NUMBER(10,2)  NOT NULL,
CONSTRAINT fk_maquinario_fazenda FOREIGN KEY (id_fazenda) REFERENCES fazenda(id_fazenda)
);