-- FAZENDAS
INSERT INTO FAZENDA (NOME, AREA_HECTARES, REGIAO) VALUES ('Fazenda Boa Vista', 350.5, 'Batatais');
INSERT INTO FAZENDA (NOME, AREA_HECTARES, REGIAO) VALUES ('Fazenda Primavera', 480.0, 'Franca');
INSERT INTO FAZENDA (NOME, AREA_HECTARES, REGIAO) VALUES ('Fazenda Santa Luzia', 290.7, 'Ribeirão Preto');

-- CULTURAS
INSERT INTO CULTURA (NOME_CULTURA, CICLO_MESES) VALUES ('Cana-de-Açúcar', 12);
INSERT INTO CULTURA (NOME_CULTURA, CICLO_MESES) VALUES ('Soja', 6);
INSERT INTO CULTURA (NOME_CULTURA, CICLO_MESES) VALUES ('Milho', 5);

-- PRODUÇÃO
INSERT INTO PRODUCAO (ID_FAZENDA, ID_CULTURA, ANO_SAFRA, QTDE_TON, CUSTO_TOTAL, RECEITA_TOTAL)
VALUES (1, 1, 2024, 12500, 980000, 1500000);
INSERT INTO PRODUCAO (ID_FAZENDA, ID_CULTURA, ANO_SAFRA, QTDE_TON, CUSTO_TOTAL, RECEITA_TOTAL)
VALUES (2, 2, 2024, 8400, 610000, 920000);
INSERT INTO PRODUCAO (ID_FAZENDA, ID_CULTURA, ANO_SAFRA, QTDE_TON, CUSTO_TOTAL, RECEITA_TOTAL)
VALUES (3, 3, 2024, 7300, 550000, 870000);

-- MAQUINÁRIO
INSERT INTO MAQUINARIO (NOME, TIPO, CUSTO_HORA, HORAS_TRABALHADAS, ID_FAZENDA)
VALUES ('Trator Massey 4292', 'Trator', 150, 820, 1);
INSERT INTO MAQUINARIO (NOME, TIPO, CUSTO_HORA, HORAS_TRABALHADAS, ID_FAZENDA)
VALUES ('Colheitadeira John Deere S660', 'Colheitadeira', 300, 540, 2);
INSERT INTO MAQUINARIO (NOME, TIPO, CUSTO_HORA, HORAS_TRABALHADAS, ID_FAZENDA)
VALUES ('Plantadeira Baldan', 'Plantadeira', 120, 430, 3);